 - name: Play to Find the uptime and to install nginx 
   hosts: all
   gather_facts: false
   tasks:
    # - name: Task to find the uptime
    #   ansible.builtin.command:
    #     cmd: 'uptime'
    #   register: uptimeInfo
    # - name: Task to install nginx
    #   ansible.builtin.package:
    #     name: nginx
    #     state: present
    #   become: yes
    # - name: Task to Disply the uptime 
    #   ansible.builtin.debug:
    #     msg: "Uptime: {{uptimeInfo.stdout}}"
    - name: Remove container
      community.docker.docker_container:
       name: vasgate_electricity_service
       state: absent
      
    - name: Start container with healthstatus
      become: true
      become_user: 'jenkins'
      become_method: sudo
      community.docker.docker_container:
        name: vasgate_electricity_service
     #   image: 172.16.12.5:8082/kyc-minimal-service:2
        image: "{{image_name}}"
        ignore_image: true
        state: started
        recreate: true
        network_mode: host
    #    ports:
    #      - "9797:9797"