#ABJ_BASEURL=https://10.10.54.44:8243/
ABJ_BASEURL=https://incmstpvlapp02.abujaelectricity.com:8243/
ABJ_GRANT_TYPE=client_credentials
ABJ_USERNAME_PREPAID=7031#EtranzactPrepaid
ABJ_USERNAME_POSTPAID=7032#EtranzactPostpaid
ABJ_PASSWORD_PREPAID=Tr@1n@aEdc
ABJ_PASSWORD_POSTPAID=Tr@1n@aEdc
ABJ_CLIENT_SECRET=ZEVnOGhkczFrVXFZOHdTS1JRMV90TTdac2FvYTpyWm5HZ2hoVzRhWlowSDBPYTllUWZZa3pEaDRh
ABJ_EMAIL=project@etranzact.com
ABJ_MAX_AMOUNT=100000
REDIS_URL=172.17.10.16
REDIS_PASSWORD=visionsvisions
REDIS_PORT=6379
