RUNNING_MODE=LIVE
mail-user=tony.ezeanya@etranzact.net
mail.password=Ezeant@2003
mail.smtp.host=smtp.etranzact.net
mail.smtp.auth=true
mail.smtp.debug=true
mail.smtp.port=25
mail.smtp.socketFactory.port=25
mail.smtp.socketFactory.fallback=false
mail.smtp.starttls.enable=
mail.smtp.socketFactory.class=
mail.sender=nhf@etranzact.net
enable-authentication=true
master_setup_excel=C:\\jboss-5.0.1.GA\\server\\default\\deploy\\NHF.war\\master_setup_excel
setup_excel=C:\\jboss-5.0.1.GA\\server\\default\\deploy\\NHF.war\\setup_excel
read_setup_excel=C:\\jboss-5.0.1.GA\\server\\default\\deploy\\NHF.war\\setup_excel
payment_excel=C:\\jboss-5.0.1.GA\\server\\default\\deploy\\NHF.war\\setup_excel
server_details=https://www.etranzact.net
timerThread=600000
PHONE_REGEX=((0|234)[7,8,9]\\d{9})


#EKO_PREFIX=0113#0114#0151#0152#0153#012#013#016#017#021#022#0231#0232#0233#024#025#026#027#028#029#030#031#032#033#034#035#036#037#038#091#093#095#092#094#096#102#103#104#106#101#105#107#901#902#903#904#906 
#EKO_PREFIX=000
#AUTOCLIENT_IP=172.16.10.134
#AUTOCLIENT_IP=172.16.10.70
#AUTOCLIENT_PORT=9999
#BILLPAY=http://172.16.10.134
#PHCNBRIDGE=http://172.16.10.5:8080
#VTU=http://172.16.10.45:9999
#VTUAPP=EtzVTU2
ecardDBIP=10.0.0.199
ecardDBPort=7160
ecardDBUsername=sa
ecardDBPassword=
CHANNEL_ID=02
SCHEME_CODE=900
CPAYDBIP=10.0.0.199
CPAYDBPort=7160
CPAYDBUsername=sa
CPAYDBPassword=
ecardDB133IP=10.0.0.199
ecardDB133Port=7160
ecardDB133Username=sa
ecardDB133Password=
#########################################################

SYB130_DBDRIVER = com.sybase.jdbc2.jdbc.SybDriver
SYB130_DBPWD = praW57br
SYB130_MAXPOOL = 20
SYB130_DBURI = jdbc:sybase:Tds:172.16.10.130:7160/telcodb?LITERAL_PARAMS=true&PACKETSIZE=512
SYB130_DBUSER = switchuser

MYS201_DBDRIVER = com.mysql.jdbc.Driver
MYS201_DBPWD = A123456@q89Uy1#
MYS201_MAXPOOL = 20
MYS201_DBURI = jdbc:mysql://localhost:3306/telcodb?autoReconnect=true
MYS201_DBUSER = matthew.abikoye
#MYS201_DBUSER = switchuser

MYS38_DBDRIVER = com.mysql.jdbc.Driver
MYS38_DBPWD = A123456@q89Uy1#
MYS38_MAXPOOL = 20
MYS38_DBURI = jdbc:mysql://localhost:3306/vasdb2?autoReconnect=true
MYS38_DBUSER = matthew.abikoye


PREPAID_ENDPOINT_IP = 127.0.0.1
PREPAID_ENDPOINT_PORT = 60257
###########################################################
###############ONLINE VERIFICATION SETTINGS################
#POSTPAID_ROUTES = KAN:31#36#34#3
POSTPAID_ROUTES = EKO:0113#0114#0151#0152#0153#012#013#016#017#021#022#0231#0232#0233#024#025#026#027#028#029#030#031#032#033#034#035#036#037#038#091#093#095#092#094#096#102#103|KAN:31#36#34#3|IBD:111#112#113#114#115#117#118#120#121#122#125#126#131#132#133#134#141#142#144#145#146#147#150#151#152#153#154#155#156#157#161#162#163#164#165#166#171#184#185#186#187#191#192#194#195#196#197#198#199#202#203#205#174#175#801#802#803#804#805#806#807#808#972#973#|IKJ:11#05#040#041#042#043#045#046#047#050#051#052#053#054#055#056#057#058#059#060#061#062#063#064#065#066#070#071#072#073#074#075#076#077#078#079#080#081#082#083#084#085#086#087#088#089#121#701#702#703#704#705#706#723#730#733#742#744#755#790#791#792#793#794#795#796#799#954#958#981
#EKO:0113#0114#0151#0152#0153#012#013#016#017#021#022#0231#0232#0233#024#025#026#027#028#029#030#031#032#033#034#035#036#037#038#091#093#095#092#094#096#102#103
#POSTPAID_ROUTES = EKO:0113#0114#0151#0152#0153#012#013#016#017#021#022#0231#0232#0233#024#025#026#027#028#029#030#031#032#033#034#035#036#037#038#091#093#095#092#094#096#102#103|




#EKO_PROCESSOR=com.etz.phcn.ekedc.core.EKEDCProcessor
EKO_PROCESSOR=com.etz.phcn.ekedc.cicod.EKEDCProcessor
KAN_PROCESSOR=com.etz.phcn.kedco.core.KEDCOProcessor
KAD_PROCESSOR=com.etz.phcn.kaedco.core.KAEDCOProcessor
IBD_PROCESSOR=com.etz.phcn.ibedc.core.IBEDCProcessor
IKJ_PROCESSOR=com.etz.phcn.ikedc.core.IKEDCProcessor
JOS_PROCESSOR=com.etz.phcn.jedc.core.JEDCProcessor
PVE_PROCESSOR=com.etz.phcn.privateelec.core.PrivateElecProcessor
RDM_PROCESSOR=com.etz.phcn.privateelec.core.PrivateElecRedeemed
ABJ_PROCESSOR=com.etz.phcn.aedc.core.AEDCProcessor
ENU_PROCESSOR=com.etz.phcn.eedc.core.EEDCProcessor
PHE_PROCESSOR=com.etz.phcn.phed.core.PHEDProcessor

#PREPAID MINIMUM AMOUNT
EKO_PREPAID_MIN=1000
KAN_PREPAID_MIN=100
KAD_PREPAID_MIN=100
IBD_PREPAID_MIN=100
IKJ_PREPAID_MIN=100
JOS_PREPAID_MIN=100
PVE_PREPAID_MIN=100
RDM_PREPAID_MIN=500
ABJ_PREPAID_MIN=500
ENU_PREPAID_MIN=100
PHE_PREPAID_MIN=100



POSTPAID_MAX_ROUTE_LENGTH = 4
#USERNAME_PROPERTY=3849gjhtw
#PASSWORD_PROPERTY=763kknm
POSTPAID_EKO_GPS_ENDPOINT=http://payelectricitybills.com/ekedcpayments/service.asmx?wsdl
POSTPAID_EKO_GPS_USERNAME=EPZ864576er4
POSTPAID_EKO_GPS_PASSWORD=364kch74mnp

#POSTPAID_REALTIME_POSTING_DISCOS=EKO
POSTPAID_REALTIME_POSTING_DISCOS=EKO,KAN,IBD,IKJ,JOS,KAD,ENU,ABJ

EKO_PREFERENCE=DIRECT
POSTPAID_EKO_WS_URL=http://197.253.9.226:8080/EKEDCWebServices_Pilot/webresources/
#POSTPAID_EKO_WS_URL=http://197.253.9.226:8080/EKEDCWebServices/webresources/
POSTPAID_EKO_WS_MID=103
POSTPAID_EKO_WS_ACCESS_TOKEN=xyz

POSTPAID_KAN_WS_URL=http://41.216.171.52:8080/KEDCOWebServicesV2_Pilot/webresources/
#POSTPAID_KAN_WS_URL=http://172.16.10.38:80/KEDCOWebServices/webresources/
POSTPAID_KAN_WS_MID=104
POSTPAID_KAN_WS_ACCESS_TOKEN=xyz

POSTPAID_IBD_WS_URL=http://testpay1.fetswallet.com/fetsIBEDC/rest/ibedcBillsPay


TOKEN_ENV=DEMO
JOS_WS_AUTHURL=https://api.adroitsuite.com.ng/core/auth/token/
POSTPAID_JOS_WS_BASEURL=https://api.adroitsuite.com.ng/core/energy/jed/postpaid/live/
PREPAID_JOS_WS_BASEURL=https://api.adroitsuite.com.ng/core/energy/jos/prepaid/demo/
JOS_WS_USERNAME_D=9f7fdce52d1249d_demo
JOS_WS_PASSWORD_D=v7^Ldx0@Bp=mX6t9vQ5z1&
JOS_WS_USERNAME_L=9f7fdce52d1249d_live
JOS_WS_PASSWORD_L=pa$$w0rD
JOS_PREPAID_WALLET_ID=E44AEFFB03DB79C71C29ACFB7
JOS_POSTPAID_WALLET_ID=CA4FB4D8FDBACD65912E75B8E
JOS_WS_AGENT_ID=12345

##PORT HARCOURT
PHED_WS_BASEURL=https://dlenhanceuat.phed.com.ng/dlenhanceapi/Collection/
PHED_APIKEY=2E639809-58B0-49E2-99D7-38CB4DF2B5B2
PHED_USERNAME=phed
PHED_CUSTOMER_DEFAULT_EMAIL=vas.banking@etranzact.com
PHED_CUSTOMER_DEFAULT_PHONE=2348035024503

POSTPAID_DISCOS=EKO,KAN,IBD,IKJ,JOS,KAD,PHE,ABJ

POSTPAID_EKO_LOCAL_FALLBACK=false
POSTPAID_KAN_LOCAL_FALLBACK=true
POSTPAID_KAN_VIRTUAL_LOCAL_FALLBACK=true
POSTPAID_JOS_LOCAL_FALLBACK=false
POSTPAID_IBD_LOCAL_FALLBACK=false
POSTPAID_IKJ_LOCAL_FALLBACK=false
POSTPAID_KAD_LOCAL_FALLBACK=false
POSTPAID_ABJ_LOCAL_FALLBACK=false
#####################################################
#PREPAID                                            
#####################################################
# This is a configuration file with default parameters that direct 
##############################################################

#DBURL = jdbc:sybase:Tds:172.16.10.130:7160/ecarddb?LITERAL_PARAMS=true&PACKETSIZE=512
SERVICE_PORT = 2345
TIMEOUT = 30
KEY_DIR = C:\\IPayBridge\\cfg\\.keystore
KEY_PWD = password
TRUST_DIR = C:\\IPayBridge\\cfg\\phcn
TRUST_PWD = password
#IPAY_IP = 41.204.194.188 - former,probably test bed
#IPAY_IP = 41.73.128.218 - not functioning
#IPAY_IP = 62.173.38.154
#IPAY_PORT = 8914
EKO_IPAY_IP = 197.253.10.213
EKO_IPAY_PORT = 8056
ISSSL = 0
REVMAXCNT = 0
#####################################################################
#SYNTELL CONNECTION PARAMETERS
#####################################################################
SYNTELL_CLIENT_ID = ETRANZACT01
SYNTELL_LOCAL_AUTHCODE = ABU
SYNTELL_OPERATOR = etzuser
SYNTELL_PARTNER_ID = 027
SYNTELL_SECURITY_KEY = 41371555
SYNTELL_TERMINAL_ID = ETRANZACT001
#####################################################################
#GPS CONNECTION PARAMETERS
#####################################################################
GPS_CLIENT_ID = ETZ
GPS_AUTH_NAME = ETZLTD
GPS_AUTH_PASS = password
GPS_TERMINAL_ID = 000000000001
GPS_OPERATOR_ID = operator
#####################################################################
#JOS_IPAY_IP = 192.168.1.132
#JOS_IPAY_IP = 172.16.10.45
JOS_IPAY_IP = 196.14.30.33
#JOS_IPAY_PORT = 8801
JOS_IPAY_PORT = 8457
ABJ_IPAY_IP = 196.14.30.33
ABJ_IPAY_PORT = 8870
ABJ_GATEWAY=EtranzactASM
ENUGU_IP = 41.73.228.162:8080
ENUGU_MID = 107

FCMB_IKJ_DEALERCODE = IE0023
#FCMB_IKJ_DEALERCODE = IE0087
FCMB_IKJ_APIKEY = d2c3bada-6d18-436c-b7e7-a1f93d064876
#FCMB_IKJ_APIKEY = aea4cd3e-38dc-4c85-9310-e267d452c720
#FCMB_IKJ_WSURL = https://www.iepins.com.ng/api/vproxy.asmx
FCMB_IKJ_WSURL = http://demoapi.iepins.com.ng/API/vproxy.asmx


FCMB_IBD_DEALERCODE = IE0023
FCMB_IBD_APIKEY = d2c3bada-6d18-436c-b7e7-a1f93d064876
FCMB_IBD_WSURL = http://fets.phcnpins.com/API/vproxy.asmx


PRIVATEELEC_WS_URL=http://172.16.10.148:8080/MEMMCOLWebServices/webresources/
PRIVATEELEC_WS_MID=103


PRIVATEELEC_RDM_WS_URL=http://172.16.10.144:8080/RCCGWebServices/webresources/
PRIVATEELEC_RDM_WS_MID=103
PRIVATEELEC_RDM_COMM_MIN=100
PRIVATEELEC_RDM_COMM_MAX=2000
PRIVATEELEC_RDM_COMM=2
PRIVATEELEC_RDM_VAT=5

ABJ_USERNAME=09cc4f8d76f2_demo
ABJ_PASSWORD=bCG#v4*Mj0*TZb9_g7uW^
ABJ_BASEURL=http://api.kvg.com.ng/demo/energy/aedc/prepaid
ABJ_HASH=0192572A2678DA5ADC5CD8B9B
ABJ_MAX_AMOUNT=100000
ABJ_AUTH_URL=http://api.kvg.com.ng/auth/demo

#ABJ_USERNAME=87638b207a3c_live
#ABJ_PASSWORD=eTranzact@1234
#ABJ_BASEURL=http://api.kvg.com.ng/live/energy/aedc/prepaid
#ABJ_HASH=0192572A2678DA5ADC5CD8B9B
#ABJ_MAX_AMOUNT=100000
#ABJ_AUTH_URL=http://api.kvg.com.ng/auth/live

ENU_API_KEY=eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eNo8jEEKwyAQAP_iOQStoOAt2BZ66R827hI8aIqrpLT0791eehuGYd4KBqqgDlrVpHiswvbkhQukBbERsygTQzThfAnuGhYfTJQA9wK53qGQBNxhy3WbqTeoL0h9TnuRaDC1G_6nmLm3nPpPWTMpej4ErPbGeeu0_nwBAAD__w.QtYWCd_zJSqThxfMXVPy7R6o2-J-SA1Q9mJLoEoHHGEc7nLsEPeMFEpj-J6BYLX9tYwvUHrA25VEDCwKevifXg
ENU_BASEURL=https://dev.myeedc.com/cashcollection/business/api/
ENU_DEFAULT_MOBILE=07051120776
ENU_ORIGIN=staging.etranzact.com
ENU_TIMEDOUT=20
ENU_LOOKUP_DELAY=3
ENU_LOOKUP_RETRY=3

#JOS SSL
#KEYSTORE_DIR=/usr/local/share/vasgate/bin/cfg/store/.keystore/etranzact_keystore.jks
#KEYSTORE_PKCS12=/usr/local/share/vasgate/bin/cfg/store/.keystore/etranzact.p12
#KEYSTORE_PWD=visions
#TRUSTSTORE_DIR=/usr/local/share/vasgate/bin/cfg/store/truststore.jks
#TRUSTSTORE_PWD=visions


KAD_WS_URL=http://104.131.174.54:4096/api/v1.0
KAD_WS_USERNAME=3tranzact
KAD_WS_PASSWORD=3tranzact
KAD_ACCESSTOKEN_TIMEOUT_MIN=700

KAD_NEW_GRANT_TYPE=client_credentials
KAD_NEW_CLIENT_ID=531724EA-5BB8-40D7-9410-E673F0E2909F
KAD_NEW_CLIENT_SECRET=9A597628-9A3C-4E4E-AAF7-BFB908F38E38
KAD_NEW_ACCESSTOKEN_TIMEOUT=3600
KAD_NEW_TOKEN_BASEURL=https://stskecs-slot.azurewebsites.net


EKO_CICOD_ENABLE=true
EKO_CICOD_WS_URL=http://dev1.convergenceondemand.net:28080/UCG/BankPartner/Endpoint
EKO_CICOD_TIMEOUT=19
EKO_CICOD_TENANT_ID=EKEDP
EKO_CICOD_ACCESS_KEY=123456
EKO_CICOD_APP_ID=ETRANZACT
EKO_WEBHOOK=http://demo.etranzact.com/vasgateWebhook/ekedp
EKO_CICOD_TOKEN_CHECK_DELAY=3
EKO_CICOD_TOKEN_RETRY_COUNT=3


#EKO_CICOD_ENABLE=true
#EKO_CICOD_WS_URL=https://prod1.convergenceondemand.net/UCG/BankPartner/Endpoint
#EKO_CICOD_TIMEOUT=20
#EKO_CICOD_TENANT_ID=EKEDP
#EKO_CICOD_ACCESS_KEY=BLV21YOBY7I0YMJUTAAOCGJTCNU4MU
#EKO_CICOD_APP_ID=ETRANZACT
#EKO_WEBHOOK=http://www.etranzact.net/vasgateWebhook/ekedp
#EKO_CICOD_TOKEN_CHECK_DELAY=3
#EKO_CICOD_TOKEN_RETRY_COUNT=5

ENABLE_STRICT_MERCHANTCODE_CHECK=false


IBEDC_URL=http://testpay1.fetswallet.com:65500/fetsIBEDC/rest/ibedcAgentBillsPay
#IBEDC_URL_LIVE=http://testpay1.fetswallet.com:65500/fetsIBEDC/rest/ibedcAgentBillsPay
IBEDC_MERCHANT_REF=0001
CHANNEL_NAME=Capricorn
REDIS_URL=redis://:visionsvisions@172.17.10.16:6379/1
IBEDC_WALLET=2347018186530
IBEDC_PASSWORD=123456
