EKOEDC_GRANT_TYPE=password
EKOEDC_USERNAME=7109#etranzactLtd
EKOEDC_PASSWORD=N@2526n
EKOEDC_CLIENT_SECRET=MXJ4UkF0ak00aXlyb2FtQlRhSmdRR2lZanM4YToxVGNUQnIxU21ITmZnMmV0cXB1RVdObmhpOE1h
EKOEDC_BASEURL=https://197.248.183.109/ekedc/
REDIS_URL=172.17.10.16
REDIS_PASSWORD=visionsvisions
REDIS_PORT=6379