#spring.application.name=ekoedc
#server.port=8585

#spring.redis.host=remote_redis_host
#spring.redis.port=6379
#spring.redis.password=your_password

EKOEDC_GRANT_TYPE=password
EKOEDC_PREPAID_USERNAME=7109#etranzactLtd
EKOEDC_POSTPAID_USERNAME=7132#etranzactPost
EKOEDC_PREPAID_PASSWORD=1@m@CCP
EKOEDC_POSTPAID_PASSWORD=1@m@CCP
EKOEDC_CLIENT_SECRET=MXJ4UkF0ak00aXlyb2FtQlRhSmdRR2lZanM4YTpwWjJFYndOX1drTmZrMGZ5T0dYOG1XSGVoRWdh
EKOEDC_BASEURL=https://192.168.213.71:21443/
#EKOEDC_CRITERIA=[{"codType":"MY003","description":"Search by meter number(mr)","default":1},{"codType":"MY001","description":"Search by AccountNumber(ac)","default":0},{"codType":"MY002","description":"Search by customer identification(cu)","default":0},{"codType":"MY004","description":"Search by Driver Licence(dl)","default":0},{"codType":"MY005","description":"Search by Old Account(oa)","default":0}]
#REDIS_URL=redis://:visionsvisions@172.17.10.76/1
#REDIS_URL=redis://:visionsvisions@172.17.10.76:6379/1
REDIS_URL=172.17.10.16
REDIS_PASSWORD=visionsvisions
REDIS_PORT=6379
EKOEDC_PING_METER_NUMBER=701362857
EKO_PING_MOBILE='08101835655'
BUYPOWER_BASE_URL=https://idev.buypower.ng/v2/
BUYPOWER_PUBLIC_KEY=7883e2ec127225f478279f0cb848e3551eaaa99d484ec39cf0b77a9ccf1d9d0d
EKO_PAYMENT_TYPE=B2B