KAN_VENDOR_ID=104
KAN_ACCESS_TOKEN=HlCCn6Rh8GqrV3GJc8JPuWBMITIa2srIyHWoiJEted807196
KAN_BASE_URL=https://ds-staging.venntech.net/api/v3/v
KAN_QUERY=/query_meter
KAN_PROCESS=/payment_notify
KAN_PING_NUMBER=94100717308
REDIS_URL=172.17.10.16
REDIS_PORT=6379
REDIS_PASSWORD=visionsvisions
#server.port=9329
