#spring.application.name=jedc
POSTPAID_JOS_WS_BASEURL=https://energize.com.ng/api/sandbox/
PREPAID_JOS_WS_BASEURL=https://energize.com.ng/api/sandbox/
JOS_WS_TOKEN=7gca88gf67ggh
JOS_WS_PRIVATE_KEY=h4i3uy4yt4ytuyty3t4lt3yty3tk4uyu5ut3yty3t4lk4
JOS_VERIFY_ENDPOINT=verifyAccount.php
JOS_MAKEPAYMENT_ENDPOINT=makePayment.php
JOS_WALLETBALLANCE_ENDPOINT=walletBalance.php
JOS_VERIFYPAYMENT_ENDPOINT=verifyPayment.php
JOS_TRANSACTIONHISTORY_ENDPOINT=transactionHistory.php
JOS_PING_METERNO=44000316354
REDIS_URL=172.17.10.16
REDIS_PORT=6379
REDIS_PASSWORD=visionsvisions
#server.port=9329
