ENU_API_KEY=eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eNo8jLEOwjAMRP_Fc4XauErBGyML_5DErpQhFMWJCkL9d8zCTU93T_eB0BkIdokwgPZojIjGJaQrcxVVqy5nWh1FpHWiOJPzJvBWQn7cQxETyltzk1Paii1dpd74_8RZW82p_SrnB5DXEwhxXCa_jJbjCwAA__8.pjb7TnUl208V65-c6gXfEzCZq9g3vr5pH7bQVmLE6QeLnUWA46WLMlXNbBdoxQDiDEaBqZplmr1iPoAMleKgSA
ENU_BASEURL=https://cashcollectiondev.myeedc.com/cashcollection/business/api/
ENU_DEFAULT_MOBILE=7051120776
ENU_LOOKUP_DELAY=3
ENU_LOOKUP_RETRY=3
ENU_ORIGIN=staging.etranzact.com
ENU_TIMEOUT=20
PHONE_REGEX=((0|234)[7,8,9]\d{9})
REDIS_PASSWORD=visionsvisions
REDIS_PORT=6379
REDIS_URL=172.17.10.16
EEDC_PING_ACCOUNT=1011074899

enu_baseurl="https://cashcollectiondev.myeedc.com/cashcollection/business/api/"
